name: Make container image

on:
  pull_request:
  workflow_dispatch:

jobs:
  container-image-release:
    name: Make container image release
    uses: nrkno/sofie-github-workflows/.github/workflows/container-build-push.yml@main
